# Generated by Django 3.0.8 on 2020-07-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200720_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='date_of_creation',
            new_name='doc',
        ),
    ]
