# Generated by Django 3.0.8 on 2020-07-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200720_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='Notes',
        ),
    ]
